name: AQA 

on: 
  push:
    branches:
    - main
        
  schedule:
   - cron: "0 2 * * 1-5"

jobs:
  aqa_test:
    name: run build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Installing NPM dependencies and run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
